version: 2.1

jobs:
  build:
    docker:
      - image: alpine:latest
    working_directory: ~/cimg-base-buildx
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.12
      - run:
          name: Build docker image
          command: ./build.sh --appendtag="-<< pipeline.git.revision >>" --push

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build