version: 2.1

jobs:
  build-and-push:
    description: Builds the image and pushes it.
    parameters:
      cimg-version:
        description: Version of cimg
        type: string
        default: "stable-18.04"
      buildx-version:
        description: Version of buildx
        type: string
        default: "0.4.1"
    docker:
      - image: docker:latest
    working_directory: ~/cimg-base-buildx
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.12
      - run:
          name: Build docker image
          command: ./build.sh --cimg-version="<< parameters.cimg-version >>" \
                              --buildx-version="<< parameters.buildx-version >>" \
                              --appendtag="-<< pipeline.git.revision >>" \
                              --push

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-push